# Site settings
title: Aleksandar Josic
email: aleksa_josic@hotmail.com.com
description: "Aleksandar Josic Portfolio"
keywords: "your keywords, separated by commas"
skills: "AR/VR Development - Unity/C#"
meta_author: Aleksandar Josic

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
email: xayvqnaa

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7f8084 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 262526 #FD6E8A
  secondary-dark: afb2b7 #A2122F

# Footer settings
footer:
  copyright: Aleksandar Josic
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/HolyManoly
  - title: linkedin
    url: https://www.linkedin.com/in/aleksandarjosic/

# Postal address (add as many lines as necessary)
address:
  - line: Kirkland, WA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
